name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          NODE_ENV: development
          DATABASE_LOCAL: mongodb://localhost:27017/SpeedySprinters
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          PORT: 3000
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN: 90d
          JWT_COOKIE_EXPIRES_IN: 90
        run: npm test
